cart/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from cart import views


app_name="cart"
urlpatterns = [
    path('add_to_cart/<int:p>/',views.add_to_cart,name="add_to_cart"),
    path('cart_view',views.cart_view,name="cart_view"),
    path('decreaser/<int:p>/',views.decreaser,name="decreaser"),
    path('delete/<int:p>/',views.delete,name="delete"),
    # path('orderform',views.order,name="order"),
    path('yourorders',views.u_r_orders,name="u_r_orders"),

]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from search import views

app_name="search"

urlpatterns = [
    path('searchresult/',views.searchresult,name="searchresult"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name="shop"

urlpatterns = [
    path('', views.allProdCat,name="allProdCat"),
    path('allproducts/<slug:cslug>', views.allproducts, name="allproducts"),
    path('prodetail/<slug:pslug>', views.prodetail, name="prodetail"),
    path('register/',views.register,name="register"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),


]

cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User

class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    date_added=models.DateField(auto_now_add=True)
    quantity=models.IntegerField(default=1)
    active=models.BooleanField(default=True)
    def subtotal(self):
        return self.quantity*self.products.price
    def __str__(self):
        return self.products.name
class Account(models.Model):
    acctnumber=models.CharField(max_length=200)
    accttype=models.CharField(max_length=200)
    amount=models.IntegerField()
    def __str__(self):
        return self.acctnumber
class Orders(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    products=models.ForeignKey(Product,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.CharField(max_length=100)

    order_status=models.CharField(max_length=30,default="Pending")
    delivery_status=models.CharField(max_length=30,default="Pending")
    noofitems=models.IntegerField()



    date_added=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.user.username
    def subtotal(self):
        return self.noofitems*self.products.price

search/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from shop.models import Product
from cart.models import Cart
from cart.models import Account,Orders
# import razorpay

from django.http import HttpResponse
@login_required
def cart_view(request):
    total=0
    try:
        user=request.user
        cart=Cart.objects.filter(user=user)
        for i in cart:
            total +=i.quantity*i.products.price
    except Cart.DoesNotExist:
        pass
    return render(request,'cart.html',{'cart':cart,'total':total})



@login_required
def add_to_cart(request,p):
    product=Product.objects.get(id=p)
    user=request.user
    try:
        cart=Cart.objects.get(products=product,user=user)
        if cart.quantity<cart.products.stock:
            cart.quantity += 1
        cart.save()
    except Cart.DoesNotExist:
        cart=Cart.objects.create(products=product,user=user,quantity=1)
        cart.save()
    return redirect('cart:cart_view')
@login_required
def decreaser(request,p):
    user=request.user
    product = Product.objects.get(id=p)
    try:
        cartitem=Cart.objects.get(products=product,user=user)
        if cartitem.quantity>1:
            cartitem.quantity -=1
            cartitem.save()
        else:
            cartitem.delete()

    except:
        pass
    return redirect('cart:cart_view')
@login_required
def delete(request,p):
    product = Product.objects.get(id=p)
    user=request.user
    try:
        cart_item=Cart.objects.get(products=product,user=user)
        cart_item.delete()
    except:
        pass
    return redirect('cart:cart_view')
# @login_required
# def order(request):
#     total=0
#     items=0
#     msg=0
#     if (request.method == "POST"):
#         ad=request.POST['ad']
#         ph=request.POST['ph']
#         ac=request.POST['ac']
#         user=request.user
#         cart=Cart.objects.filter(user=user)
#         for i in cart:
#             total+=i.quantity*i.products.price
#             items+=i.quantity
#             a=Account.objects.get(acctnumber=ac)
#             if float(a.amount) >=total:
#                 a.amount=a.amount-total
#                 a.save()
#                 for i in cart:
#                     o=Orders.objects.create(user=user,products=i.products,address=ad,phone=ph,order_status="paid",noofitems=i.quantity)
#                     o.save()
#                 cart.delete()
#                 msg="Order placed succesfully!!!"
#                 return render(request,'orderdetail.html',{'msg':msg,'total':total,'items':items})
#             else:
#                 msg="insufficient Amount.You cant place order!!"
#                 return render(request,'orderdetail',{'msg':msg})
#     return render(request,'form.html')
from django.conf import settings
import razorpay
# @login_required
# def order(request):
#     total = 0
#     items = 0
#     msg = 0
#
#     try:
#         user = request.user
#         cart = Cart.objects.filter(user=user)
#         for i in cart:
#             total += i.quantity * i.products.price
#             items += i.quantity
#     except Cart.DoesNotExist:
#         pass
#
#     client = razorpay.Client(auth=(settings.RAZOR_PAY_KEY_ID))
#
#     # Create a Razorpay order
#     order_amount = int(total * 100)  # Razorpay amount is in paisa
#     order_currency = 'INR'
#     order_receipt = 'order_rcptid_11'
#     payment = client.order.create(amount=order_amount, currency=order_currency, receipt=order_receipt)
#
#     msg = "Order placed successfully!!!"
#     return render(request, 'orderdetail.html', {'msg': msg, 'payment': payment, 'items': items})



@login_required
def u_r_orders(request):
    user= request.user
    o= Orders.objects.filter(user=user,order_status="paid")

    return render(request,'your orders.html',{'o':o,'name':user})

search/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q
from django.http import HttpResponse

def searchresult(request):
    products=None
    query=None
    if request.method=="POST":
        query=request.POST.get('q')
        if query:
            products=Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request,'search.html',{'query':query,'products':products})

# Create your views here.

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="{% static 'js/checkout.js' %}"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;1,300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.css" integrity="sha512-0SPWAwpC/17yYyZ/4HSllgaK7/gg9OlVozq8K7rf3J8LvCjYEEIfzzpnA2/SSjpGIunCSD18r3UhvDcu/xncWA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.min.js" integrity="sha512-ooSWpxJsiXe6t4+PPjCgYmVfr1NS5QXJACcR/FPpsdm6kqG1FmQ2SVyg2RXeVuCRBLr0lWHnWJP6Zs1Efvxzww==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.12/cropper.css" integrity="sha512-+VDbDxc9zesADd49pfvz7CgsOl2xREI/7gnzcdyA9XjuTxLXrdpuz21VVIqc5HPfZji2CypSbxx1lgD7BgBK5g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
</head>
<body>
<div class="container-fluid">
    <header>
        <center><img src="{% static 'img/logo.jpg' %}" height="100px" width="200px"></center>
        <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color:rgb(160, 168, 173);">
     <div class="container-fluid">
    <a class="navbar-brand" href="#">E-cart</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:allProdCat' %}">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Shop
          </a>

             {% if user.is_authenticated %}
          <li class="nav-item">
           <a class="btn btn-primary" href="{% url 'cart:cart_view'  %}"><i class="fa-solid fa-cart-shopping">Cart</i>{{item_count}}</a>
        </li>
                 <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'cart:u_r_orders' %}">Your Orders</a>
        </li>
                 <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
        </li>
          {% else %}
            <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'shop:login' %}">Login</a>
        </li>
          {% endif %}

          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Categories</a></li>
              {% for i in links %}

            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.slug %}">{{i.name}}</a></li>
              {% endfor %}

          </ul>
        </li>
      </ul>
      <form class="d-flex" action="{% url 'search:searchresult' %}" method="POST">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>
    </header>
        {% block content %}
        {% endblock %}

        {% block scripts %}
        {% endblock scripts %}
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
        <script src="{% static 'js/checkout.js' %}"></script>




        <footer class="footer">
            <div>
                <p><i class="fa-solid fa-copyright"></i>&copy;Myshop pvt ltd.All rights reserved.</p>
            </div>
        </footer>

</div>
</body>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container" style="margin-bottom:100px">
    {% if not cart %}
    <div>
        <h1 class="text-center">Cart is empty</h1>
    </div>
    <div>
        <strong><a href="{% url 'shop:allProdCat' %}">Continue shopping</a></strong>
    </div>
    {% else %}
    <div class="row mx-auto">
        <h1 style="width:100%;">Shopping cart</h1>

        <div class="col-sm-6">
            <table class="table table-bordered">
                <tr>
                <th colspan="5">
                    YOUR ITEMS
                </th>
                {% for i in cart %}
                <tr>
                <td><img src="{{i.products.image.url}}" style="hieght:150px;width:150px"></a></td>
                <td>{{i.products.name}}</td>
                <td>{{i.products.id}}<br>
                 Unit Price:{{i.products.price}}<br>
                quantity:{{i.quantity}}*{{i.products.price}}<br>

                </td>
                <td>{{i.subtotal}}</td>
                {% if i.quantity < i.products.stock %}
                <td><a href="{% url 'cart:add_to_cart' i.products.id %}"><i class="fa-solid fa-plus"></i></a></td>
                <td><a href="{% url 'cart:decreaser' i.products.id %}"><i class="fa-solid fa-minus"></i></a></td>
                <td><a href="{% url 'cart:delete' i.products.id %}"><i class="fa-solid fa-trash"></i></a></td>
                </td>
                 {% else %}
                 <td><a href="{% url 'cart:decreaser' i.products.id %}"><i class="fa-solid fa-minus"></i></a></td>
                <td><a href=""><i class="fa-solid fa-trash"></i></a></td>
                {% endif %}

            </tr>
                {% endfor %}
            </table>
        </div>
        {% endif %}
    <div class="col-sm-6">
        <table class="table">
            <tr>
            <th colspan="5">Checkout</th></tr>
            <tr>
                <th>TOTAL PRICE:{{total}}</th>
            </tr>

        </table>
         <a href="{% url 'shop:allProdCat' %}"><button class="btn btn-outline-success" href="">CONTINUE SHOPPING</button></a>
        <button id="rzp-button1">Pay with Razorpay</button>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "rzp_test_2voTrBZq69eFuI",
    "amount": 10000, // 100 INR in paise
    "currency": "INR",
    "name": "Acme Corp",
    "description": "Test Transaction",
    "image": "https://example.com/your_logo",
    "order_id": "order_IluGWxBm9U8zJ8", // Replace with the actual order ID
    "handler": function (response){
        alert(response.razorpay_payment_id);
        alert(response.razorpay_order_id);
        alert(response.razorpay_signature);
    },
    "prefill": {
        "name": "Gaurav Kumar",
        "email": "example@example.com",
        "contact": "9000090000"
    },
    "notes": {
        "address": "Razorpay Corporate Office"
    },
    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
    alert(response.error.code);
    alert(response.error.description);
    alert(response.error.source);
    alert(response.error.step);
    alert(response.error.reason);
    alert(response.error.metadata.order_id);
    alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
};
</script>


</script>
    </div>
</div>
</div>
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{% static 'img/banner.jpg' %}" height="600px" width="100%">
</div>
<div style="margin-bottom:100px;">
<h1 class="text-center">Our Collections</h1>
   <p class="text-justify">Leaving shoppers’ questions unanswered can derail a sale or even worse, make shoppers abandon not just the purchase, but the site as well. One shopper in a recent study could not find the information he needed in the product description, so he left the site to search Google for more product information.</p>
</div>
  <div class="container" style="margin-bottom:300px;">
<div class="row mx-auto">
  {% for i in c %}
  <div class="col-sm-4">
    <div class="card" style="width: 20rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="{{i.name}}" height="300px;" width="100%;">
  <div class="card-body" style="poistion:relative;">
    <h5 class="card-title title_heading">{{i.name}}</h5>
    <a href="{% url 'shop:allproducts' i.slug%}" class="btn btn-primary link">PRODUCTS</a>
  </div>
  </div>
  </div>
  {% endfor %}


</div>
</div>

{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="conatiner">
    <div class="row">
        <div class="col-sm-6">
            <img src="{{p.image.url}}" alt="{{p.image.url}}">
        </div>
        <div class="col-sm-6">
            <div>
                <h1>Name:{{p.name}}</h1>
                <p>{{p.price}}</p>
                <p>{{p.description}}</p>
                 <h3>Product Description</h3>
                {% if p.stock <= 0 %}
                <h2>OUT OF STOCK</h2>
                {% else %}
                <a class="btn btn-primary" href="{% url 'cart:add_to_cart' p.id %}"><i class="fa-solid fa-cart-shopping"></i></a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
  {% csrf_token %}
<center>
  <div class="mb-3">
  <label for="formGroupExampleInput" class="form-label">ADDRESS</label>
  <input type="text-area" class="form-control" id="formGroupExampleInput" name="ad" placeholder="Please Enter you Address">
</div>
<div class="mb-3">
  <label for="formGroupExampleInput2" class="form-label">PHONE</label>
  <input type="text" class="form-control" id="formGroupExampleInput2" name="ph" placeholder="Please Enter you phone number">
</div>
<div class="mb-3">
  <label for="formGroupExampleInput2" class="form-label">ACCOUNT-NUMBER</label>
  <input type="text" class="form-control" id="formGroupExampleInput3" name="ac" placeholder="Please Enter you Account NUmber">
</div>
<button type="submit" class="btn btn-primary">SUBMIT</button>
  </center>
</form>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="bg-light">
      <h3>Login</h3>
<div class="mb-3">
    <label for="form-label">UserName</label>
    <input type="text" class="form-control" name="u" placeholder="first name">
  </div>
<div class="mb-3">
    <label for="form-label">Password</label>
    <input type="password" class="form-control" name="p" placeholder="first name">
  </div>
        <div class="mb-3">
     <button class="btn btn-outline-danger" type="submit">Submit</button>
  </div>
    </div>
</form>
{% if messages %}
{% for i in messages %}
<ul class="messages">
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}

{% endblock %}

templates/orderdetail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}add{% endblock %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <h1>Order Detail</h1>
    {{total}}
    {{msg}}
    {{items}}
</div>
{% endblock %}

templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    <img src="{{c.image.url}}" height="600px" width="100%">
</div>
<div style="margin-bottom:100px;">
<h1 class="text-center">{{c.name}}</h1>
   <p class="text-justify"></p>
</div>
  <div class="container" style="margin-bottom:300px;">
<div class="row mx-auto">
  {% for i in p %}
  <div class="col-sm-4">
    <div class="card" style="width: 20rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="{{i.name}}" height="300px;" width="100%;">
  <div class="card-body" style="poistion:relative;">
    <h5 class="card-title title_heading">{{i.name}}</h5>
    <a href="{% url 'shop:prodetail' i.slug %}" class="btn btn-primary link">DETAILS</a>
  </div>
  </div>
  </div>

{% endfor %}
</div>
</div>

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <div class="bg-secondary">
    <h3>Sign-Up</h3>
         <div class="mb-3">
    <label for="form-label">UserName</label>
    <input type="text" class="form-control" name="u" placeholder="user name">
  </div>
  <div class="mb-3">
    <label for="form-label">FirstName</label>
    <input type="text" class="form-control" name="fs" placeholder="first name">
  </div>
    <div class="mb-3">
      <label for="form-label">LastName</label>
    <input type="text" class="form-control" name="ls" placeholder="last name">
    </div>
    <div class="mb-3">
        <label for="form-label">E-Mail</label>
      <input type="email" class="form-control" name="e" placeholder="enter your mail">
    </div>
  <div class="mb-3">
        <label for="form-label">Password</label>
      <input type="password" class="form-control" name="p" placeholder="enter your password">
    </div>
  <div class="mb-3">
        <label for="form-label">Confirm-password</label>
      <input type="password" class="form-control" name="cp" placeholder="confirm your password">
    </div>
  <div class="mb-3">
     <button class="btn btn-outline-danger" type="submit">Submit</button>
  </div>
        </div>
</form>
{% if messages %}
{% for i in messages %}
<ul class="messages">
    <li>{{i}}</li>
</ul>
{% endfor %}
{% endif %}
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<div>
    <h3>you have searched for{{query}}</h3>
</div></center>

  <div class="container" style="margin-bottom:300px;">
<div class="row mx-auto">
  {% for i in products %}
  <div class="col-sm-4">
    <div class="card" style="width: 20rem;">
  <img src="{{i.image.url}}" class="card-img-top" alt="{{i.name}}" height="300px;" width="100%;">
  <div class="card-body" style="poistion:relative;">
    <h5 class="card-title title_heading">{{i.name}}</h5>
    <a href="{% url 'shop:prodetail' i.slug %}" class="btn btn-primary link">DETAILS</a>
  </div>
  </div>
  </div>
  {% empty %}
  <div>
    <p>0 RESULTS FOUND</p>
  </div>

 {% endfor %}
</div>
</div>

{% endblock %}

templates/your orders.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:420px;">
  <div class="row max-auto">
  <h3>Name of the customer:{{name}}</h3>
    {% for p in o %}
    <div class="col-sm-6" style="border:1px solid black;">
      <img src="{{p.products.image.url}}" height="200px;" width="200px;" alt="{p.products.image.url}}">
    </div>
    <div class="col-sm-6" style="border:1px solid black;">
        delivery address: {{p.address}}<br>
        phone number: {{p.phone}}<br>
        {{p.products.name}}<br>
        {{p.products.price}}<br>
        quantity ordered: {{p.noofitems}}<br>
        subtotal: {{p.subtotal}}<br>
        <strong>order on: {{p.date_added}}</strong><br>
        <strong class="text-success">delivery status:{{p.delivery_status}}</strong>

      </div>
      {% endfor %}
    </div>

</div>
</div>
{% endblock %}